export const SHEET_ID = "1iFUyaMhrA_HutzpgV88imc9peWfH_4ovyjLIFj33E-U";
export const TAB_NAMES = [
  "OVERVIEW",
  "Sheet1",
  "AUDIO",
  "LIGHTING",
  "VIDEO - LED",
  "LASER",
  "SFX - PYRO",
  "POWER",
  "RIGGING",
  "BACKLINE",
  "BROADCAST",
  "STAGING",
] as const;

export const EMBEDDED_SHEET_DATA = {
  "OVERVIEW": {
    "title": "OVERVIEW",
    "headline": "EC26 Electric Castle Mainstage — Advancing Sheet",
    "rowCount": 76,
    "nonEmptyRows": 71,
    "maxCols": 9,
    "rows": [
      {"rowNumber": 1, "cells": []},
      {"rowNumber": 2, "cells": ["EC26 ELECTRIC CASTLE MAINSTAGE — ADVANCING SHEET"]},
      {"rowNumber": 3, "cells": ["1. PROJECT INFORMATION"]},
      {"rowNumber": 4, "cells": ["Project Name:", "", "EC26_Electric_Castle_Mainstage v01"]},
      {"rowNumber": 5, "cells": ["Event / Festival:", "", "Electric Castle 2026"]},
      {"rowNumber": 6, "cells": ["Stage:", "", "Mainstage"]},
      {"rowNumber": 7, "cells": ["Venue:", "", "Banffy Castle Domain"]},
      {"rowNumber": 8, "cells": ["Location / Address:", "", "Banffy Castle, Bonțida, postal code 407105, Romania"]},
      {"rowNumber": 9, "cells": ["GPS Coordinates:", "", "46° 54' 33.8378\" N 23° 48' 14.7949\" E  (WR55+H7)"]},
      {"rowNumber": 10, "cells": ["Version:", "", "v01"]},
      {"rowNumber": 11, "cells": ["Date:", "", "TBD — 2026  (ref: EC25 Day 2 V2)"]},
      {"rowNumber": 12, "cells": ["DASHBOARD DESIGN:", "", "UNREAL.AE"]},
      {"rowNumber": 13, "cells": ["2. SHOW DATES"]},
      {"rowNumber": 14, "cells": ["Build Start:", "", "TBD July 2026"]},
      {"rowNumber": 15, "cells": ["Show Day 1:", "", "TBD July 2026 — Day 1"]},
      {"rowNumber": 16, "cells": ["Show Day 2:", "", "TBD July 2026 — Day 2"]},
      {"rowNumber": 17, "cells": ["Show Day 3:", "", "TBD July 2026 — Day 3"]},
      {"rowNumber": 18, "cells": ["Show Day 4:", "", "TBD July 2026 — Day 4"]},
      {"rowNumber": 19, "cells": ["Load Out End:", "", "TBD July 2026"]},
      {"rowNumber": 20, "cells": []},
      {"rowNumber": 21, "cells": ["3. PRODUCTION TEAM"]},
      {"rowNumber": 22, "cells": ["Role", "", "First Name", "", "Last Name", "", "Phone", "", "Email"]},
      {"rowNumber": 23, "cells": ["Executive Producer", "", "Titus", "", "Carole", "", "+40 755 916 020", "", "titus.carole@electriccastle.ro"]},
      {"rowNumber": 24, "cells": ["Production Manager", "", "Sem", "", "Elitas", "", "+32 476 02 28 33", "", "sem.elitas@gmail.com"]},
      {"rowNumber": 25, "cells": ["Production Manager Night", "", "Stijn (Stino)", "", "Verheyden", "", "+32 486 14 85 13", "", "stijn@stinofix.com"]},
      {"rowNumber": 26, "cells": ["Stage Manager", "", "Bjorn", "", "Ielegems", "", "+32 478 71 34 90", "", "bjorn@modemux.be"]},
      {"rowNumber": 27, "cells": ["Technical Manager"]},
      {"rowNumber": 28, "cells": ["Audio Crew Chief", "", "Lorànd", "", "Nagy", "", "+36 70 425 8226", "", "lorand@klemm-concert.hu"]},
      {"rowNumber": 29, "cells": ["Lighting Designer / Operator", "", "Andre", "", "Beekmans", "", "+31 6 21143599", "", "andre@theartoflight.nl"]},
      {"rowNumber": 30, "cells": ["Video / LED Crew Chief", "", "Bogdan", "", "Nedelcu", "", "+40 734 727 471", "", "bobo@apart.vision"]},
      {"rowNumber": 31, "cells": ["VJ & Content Creation", "", "Bogdan", "", "Nedelcu", "", "+40 734 727 471", "", "bobo@apart.vision"]},
      {"rowNumber": 32, "cells": ["Rigging Crew Chief", "", "Gabriel", "", "Neaga", "", "+40 736 924 481", "", "Gabriel@loudmusic.ro"]},
      {"rowNumber": 33, "cells": ["Power Crew Chief"]},
      {"rowNumber": 34, "cells": ["SFX / Pyro Operator", "", "Alexandru", "", "Bondria", "", "+40 729 953 001", "", "alexandru@pyroevents.ro"]},
      {"rowNumber": 35, "cells": ["Laser Operator"]},
      {"rowNumber": 36, "cells": ["Stagehand Coordinator"]},
      {"rowNumber": 37, "cells": ["Backline Responsible"]},
      {"rowNumber": 38, "cells": ["Broadcast Engineer", "", "Attila", "", "Soós", "", "+40 723 345 910", "", "attila@espadamedia.ro"]},
      {"rowNumber": 39, "cells": []},
      {"rowNumber": 40, "cells": ["4. SUPPLIERS & COMPANIES"]},
      {"rowNumber": 41, "cells": ["Discipline", "", "Company", "", "Contact Person", "", "Phone", "", "Email"]},
      {"rowNumber": 42, "cells": ["Audio", "", "Klemm Concert", "", "Lorànd Nagy", "", "+36 70 425 8226", "", "lorand@klemm-concert.hu"]},
      {"rowNumber": 43, "cells": ["Lighting", "", "The Art of Light / Colossal", "", "Andre Beekmans / Márk Kontra", "", "+31 6 21143599", "", "andre@theartoflight.nl"]},
      {"rowNumber": 44, "cells": ["Video / LED", "", "Apart Vision", "", "Bogdan Nedelcu", "", "+40 734 727 471", "", "bobo@apart.vision"]},
      {"rowNumber": 45, "cells": ["Rigging / Staging", "", "Loudmusic", "", "Serban Constantinescu", "", "+40 737 203 060", "", "serban@loudmusic.ro"]},
      {"rowNumber": 46, "cells": ["Power / Generator"]},
      {"rowNumber": 47, "cells": ["SFX / Pyro", "", "Pyroevents", "", "Alexandru Bondria", "", "+40 729 953 001", "", "alexandru@pyroevents.ro"]},
      {"rowNumber": 48, "cells": ["Lasers"]},
      {"rowNumber": 49, "cells": ["Backline"]},
      {"rowNumber": 50, "cells": ["Crew / Stagehands"]},
      {"rowNumber": 51, "cells": ["Broadcast / IMAG", "", "Espada Media", "", "Attila Soós", "", "+40 723 345 910", "", "attila@espadamedia.ro"]},
      {"rowNumber": 52, "cells": ["Security"]},
      {"rowNumber": 53, "cells": ["Catering"]},
      {"rowNumber": 54, "cells": ["Transport"]},
      {"rowNumber": 55, "cells": []},
      {"rowNumber": 56, "cells": ["5. KEY SHOW INFO"]},
      {"rowNumber": 57, "cells": ["Load In Start:", "", "TBD July 2026"]},
      {"rowNumber": 58, "cells": ["Show Open / Gate:", "", "TBD"]},
      {"rowNumber": 59, "cells": ["First Act:", "", "TBD"]},
      {"rowNumber": 60, "cells": ["Curfew / Last Act:", "", "TBD"]},
      {"rowNumber": 61, "cells": ["Load Out End:", "", "TBD July 2026"]},
      {"rowNumber": 62, "cells": ["Emergency Number:", "", "TBD"]},
      {"rowNumber": 63, "cells": ["Nearest Hospital:", "", "TBD — Bonțida area"]},
      {"rowNumber": 64, "cells": ["Site Currency:", "", "RON / EUR"]},
      {"rowNumber": 65, "cells": []},
      {"rowNumber": 66, "cells": ["TABLE OF CONTENTS — DISCIPLINE TABS"]},
      {"rowNumber": 67, "cells": ["1.", "", "→  See tab: AUDIO"]},
      {"rowNumber": 68, "cells": ["2.", "", "→  See tab: LIGHTING"]},
      {"rowNumber": 69, "cells": ["3.", "", "→  See tab: VIDEO / LED"]},
      {"rowNumber": 70, "cells": ["4.", "", "→  See tab: LASER"]},
      {"rowNumber": 71, "cells": ["5.", "", "→  See tab: SFX / PYRO"]},
      {"rowNumber": 72, "cells": ["6.", "", "→  See tab: POWER"]},
      {"rowNumber": 73, "cells": ["7.", "", "→  See tab: RIGGING"]},
      {"rowNumber": 74, "cells": ["8.", "", "→  See tab: BACKLINE"]},
      {"rowNumber": 75, "cells": ["9.", "", "→  See tab: BROADCAST"]},
      {"rowNumber": 76, "cells": ["10.", "", "→  See tab: STAGING"]},
    ],
    "metrics": {
      "sections": 19,
      "quantityTotal": 0
    },
    "sections": ["EC26 ELECTRIC CASTLE MAINSTAGE — ADVANCING SHEET", "1. PROJECT INFORMATION", "2. SHOW DATES", "3. PRODUCTION TEAM", "Technical Manager", "Power Crew Chief", "Laser Operator", "Stagehand Coordinator", "Backline Responsible", "4. SUPPLIERS & COMPANIES", "Power / Generator", "Lasers", "Backline", "Crew / Stagehands", "Security", "Catering", "Transport", "5. KEY SHOW INFO", "TABLE OF CONTENTS — DISCIPLINE TABS"]
  },
  "Sheet1": {
    "title": "Sheet1",
    "headline": "Workflow Draft — LME Staging & Rigging v1",
    "rowCount": 28,
    "nonEmptyRows": 28,
    "maxCols": 6,
    "rows": [
      {"rowNumber": 1, "cells": ["Workflow Draft LME Staging&Rigging v1"]},
      {"rowNumber": 2, "cells": ["", "", "", "", "tbd/tbc"]},
      {"rowNumber": 3, "cells": ["3/Jul", "", "Unloading Staging Trucks", "Travel Boneyard manager or PM"]},
      {"rowNumber": 4, "cells": ["4/Jul", "", "Unloading Staging Trucks", "Unloading Stage Area & Boneyard"]},
      {"rowNumber": 5, "cells": ["5/Jul", "", "Travel Headcrew , Unloadings, Spiking", "Travel for rest of the team/afternoon"]},
      {"rowNumber": 6, "cells": ["6/Jul", "", "Build day 1", "Layher Stage+ Decks Performance Area+ MF trusses near the stage"]},
      {"rowNumber": 7, "cells": ["7/Jul", "", "Build day 2", "Build Stage + Mother Grid on Stage + Towers Buid near stage done", "crane"]},
      {"rowNumber": 8, "cells": ["8/Jul", "", "Build day 3", "Roof Working Level + Prerig", "crane"]},
      {"rowNumber": 9, "cells": ["9/Jul", "", "Build day 4", "Roof Up + Layher Tent Area"]},
      {"rowNumber": 10, "cells": ["10/Jul", "", "Build day 5", "Towers Led + Led Frames + loading Areas", "crane", "Travel LED team"]},
      {"rowNumber": 11, "cells": ["11/Jul", "", "Build day 6", "Towers Led + Led Frames + Foh + Rigging", "crane", "Header Day 1"]},
      {"rowNumber": 12, "cells": ["12/Jul", "", "Productie Led, Light,", "Production Led ( Headder)+ Rigging + Staging Final Touch", "", "Header Day 2"]},
      {"rowNumber": 13, "cells": ["13/Jul", "", "Productie Led, Light, Audio", "Production Led + Rigging Lights&Audio", "", "Travel AUDIO/light Team"]},
      {"rowNumber": 14, "cells": ["14/Jul", "", "Productie All , Programare", "Production Led, Audio, Lights + Build Thrust"]},
      {"rowNumber": 15, "cells": ["15/Jul", "", "Probe/Load In Artist", "Probe/Load In Artist"]},
      {"rowNumber": 16, "cells": ["16/Jul", "Day 0", "Programming ", "Load in 21pilots "]},
      {"rowNumber": 17, "cells": ["17/Jul", "Day 1", "Showday 1", "Showday 1"]},
      {"rowNumber": 18, "cells": ["18/Jul", "Day 2", "Showday 2", "Showday 2"]},
      {"rowNumber": 19, "cells": ["19/Jul", "Day 3", "Showday 3", "Showday 3"]},
      {"rowNumber": 20, "cells": ["20/Jul", "", "Load Out Productie/ Travel Partial LME", "Rigging all deps, skins out partial, thrust, Bstage, Cort Out"]},
      {"rowNumber": 21, "cells": ["21/Jul", "", "Steel 1", "Backstage Area, Roof down"]},
      {"rowNumber": 22, "cells": ["22/Jul", "", "Steel 2", "Towers Out, Trussing+ Layher+Decks", "crane x2"]},
      {"rowNumber": 23, "cells": ["23/Jul", "", "Steel 3", "Trussing+ Layher+Decks"]},
      {"rowNumber": 24, "cells": ["24/Jul", "", "Steel 4 / Load", "Layher + Trussing + Load Partial"]},
      {"rowNumber": 25, "cells": ["25/Jul", "", "Steel out all/ Loadings/ Travel partial LME", "Steel out all/ Loadings Final + Travel Partial Staging Team"]},
      {"rowNumber": 26, "cells": ["26/Jul", "", "Travel", "Last Staging Team Travel"]},
      {"rowNumber": 27, "cells": ["", "", "", "", "", "1,25 x 2,50m"]},
      {"rowNumber": 28, "cells": ["", "", "", "", "", "55m DSE to FOH"]},
    ],
    "metrics": {
      "sections": 1,
      "quantityTotal": 0
    },
    "sections": ["Workflow Draft LME Staging&Rigging v1"]
  },
  "AUDIO": {
    "title": "AUDIO",
    "headline": "EC26 — Audio — See Attached Files",
    "rowCount": 57,
    "nonEmptyRows": 45,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — AUDIO — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["PA System"]},
      {"rowNumber": 4, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 5, "cells": ["Main PA", "", "", "L'acoustics K1 / K2down", "", "", "2 strings / 14pcs K1 / 4pcs K2down"]},
      {"rowNumber": 6, "cells": ["Outfill PA", "", "", "L'acoustics K1-SB / K1 / K2down", "", "", "2 strings / 4pcs K1-SB / 10pcs K1 / 4pcs K2 down"]},
      {"rowNumber": 7, "cells": ["Delay PA", "", "", "L'acoustics K2", "", "", "4 strings / 12pcs K2 + 4pcs KS28"]},
      {"rowNumber": 8, "cells": ["Subs", "", "48", "L'acoustics KS28", "", "", "48pcs ground-stacked"]},
      {"rowNumber": 9, "cells": ["Frontfills", "", "", "L'acoustics Kara", "", "", "11 stacks / 2pcs front"]},
      {"rowNumber": 10, "cells": ["VIP Fills"]},
      {"rowNumber": 11, "cells": ["Delay FOH"]},
      {"rowNumber": 12, "cells": []},
      {"rowNumber": 13, "cells": ["DJ & Stage Monitoring"]},
      {"rowNumber": 14, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 15, "cells": ["DJ Monitoring", "", "", "4x L'acoustics SB18 + 6x L'acoustics Kara", "", "", "e.g. 4x SB18 + 6x Kara"]},
      {"rowNumber": 16, "cells": ["Wedges", "", "12", "L'acoustics X15HiQ"]},
      {"rowNumber": 17, "cells": ["IEM Systems"]},
      {"rowNumber": 18, "cells": ["Sidefills"]},
      {"rowNumber": 19, "cells": []},
      {"rowNumber": 20, "cells": ["Consoles & Processing"]},
      {"rowNumber": 21, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 22, "cells": ["FOH Console", "", "1", "DiGiCo Quantum 338", "", "", "56ch/32ch out (incl. Waves Soundgrid)"]},
      {"rowNumber": 23, "cells": ["FOH Equipment / Processor", "", "1", "L-Acoustics P1 AVB", "", "", "Processor for 96k PA drive"]},
      {"rowNumber": 24, "cells": ["MON Console", "", "1", "Allen and Heath D-Live S7000", "", "", "MON Console"]},
      {"rowNumber": 25, "cells": ["Wireless Systems", "", "", "Axient Digital", "", "", "2x AD4Q + 8x AD2 + 8x AD1 / 8x PSM1000 + 16x P10+"]},
      {"rowNumber": 26, "cells": ["Stage Boxes / Multicores"]},
      {"rowNumber": 27, "cells": []},
      {"rowNumber": 28, "cells": ["DJ Gear"]},
      {"rowNumber": 29, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 30, "cells": ["DJ Mixer", "", "", "", "", "", "e.g. 1x DJM 900 NXS II + 1 Spare"]},
      {"rowNumber": 31, "cells": ["DJ Players", "", "", "", "", "", "e.g. 4x CDJ 2000 NXS II + 1x Spare"]},
      {"rowNumber": 32, "cells": ["Slider System"]},
      {"rowNumber": 33, "cells": ["Turntables"]},
      {"rowNumber": 34, "cells": []},
      {"rowNumber": 35, "cells": ["Communication & Misc"]},
      {"rowNumber": 36, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 37, "cells": ["Communication / Intercom", "", "10", "Greengo Intercom + Double muff headset", "", "", "e.g. Clearcom Helix"]},
      {"rowNumber": 38, "cells": ["Mics DJ & Presentation", "", "2", "Shoutbox System for Audio"]},
      {"rowNumber": 39, "cells": ["Wireless Mics (handheld)"]},
      {"rowNumber": 40, "cells": ["Ambient Mics"]},
      {"rowNumber": 41, "cells": ["Shoutbox"]},
      {"rowNumber": 42, "cells": ["Fans (Booth)"]},
      {"rowNumber": 43, "cells": []},
      {"rowNumber": 44, "cells": ["DJ Booth Setup"]},
      {"rowNumber": 45, "cells": ["House Booth:", "", "LxWxH (m)"]},
      {"rowNumber": 46, "cells": ["Headliner Booth:", "", "LxWxH (m)"]},
      {"rowNumber": 47, "cells": ["Booth Connection to FOH:", "", "e.g. 2x Ethernet + 2x CAT5"]},
      {"rowNumber": 48, "cells": []},
      {"rowNumber": 49, "cells": ["Power Requirement — Audio"]},
      {"rowNumber": 50, "cells": ["Total Audio Power (kW):"]},
      {"rowNumber": 51, "cells": []},
      {"rowNumber": 52, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 53, "cells": []},
      {"rowNumber": 54, "cells": []},
      {"rowNumber": 55, "cells": []},
      {"rowNumber": 56, "cells": []},
      {"rowNumber": 57, "cells": ["Insert PA Plot / Audio Rider / Stage Plan here"]},
    ],
    "metrics": {
      "sections": 15,
      "quantityTotal": 75.0
    },
    "sections": ["Delay FOH", "Sidefills", "Consoles & Processing", "Stage Boxes / Multicores", "Slider System", "Turntables", "Communication & Misc", "Wireless Mics (handheld)", "Ambient Mics", "Shoutbox", "Fans (Booth)", "Power Requirement — Audio", "Total Audio Power (kW):", "Notes / Remarks:", "Insert PA Plot / Audio Rider / Stage Plan here"]
  },
  "LIGHTING": {
    "title": "LIGHTING",
    "headline": "EC26 — Lighting — See Attached Files",
    "rowCount": 62,
    "nonEmptyRows": 50,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — LIGHTING — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Fixtures — Stage"]},
      {"rowNumber": 4, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 5, "cells": ["Spot / Profile", "", "41", "Robe Robin Forte", "", "", "Profile"]},
      {"rowNumber": 6, "cells": ["Beam", "", "24", "Robe Robin Pointe", "", "", "Beam"]},
      {"rowNumber": 7, "cells": ["Wash", "", "32", "Martin MAC Quantum Wash", "", "", "Wash"]},
      {"rowNumber": 8, "cells": ["Hybrid"]},
      {"rowNumber": 9, "cells": ["LED Wash"]},
      {"rowNumber": 10, "cells": ["LED Par"]},
      {"rowNumber": 11, "cells": ["LED Strip", "", "44", "Robe iBar 15", "", "", "LED Strip / Bar"]},
      {"rowNumber": 12, "cells": ["LED FX"]},
      {"rowNumber": 13, "cells": ["Strobe", "", "48", "Robe Robin Colorstrobe", "", "", "Strobe"]},
      {"rowNumber": 14, "cells": ["Blinder", "", "50", "Thomas 2+4 Lite Par 36", "", "", "24x 2-Lite + 26x 4-Lite Par 36"]},
      {"rowNumber": 15, "cells": ["Followspot", "", "10", "Robe iForte LTX FS", "", "", "6x FS + 4x Delay, 2 pcs Stage"]},
      {"rowNumber": 16, "cells": []},
      {"rowNumber": 17, "cells": ["Fixtures — Wings"]},
      {"rowNumber": 18, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 19, "cells": ["Beam", "", "48", "Robe Robin LEDBeam 350", "", "", "Wing washlights"]},
      {"rowNumber": 20, "cells": ["Wash"]},
      {"rowNumber": 21, "cells": ["LED Flood"]},
      {"rowNumber": 22, "cells": ["LED Strobe"]},
      {"rowNumber": 23, "cells": ["Blinder"]},
      {"rowNumber": 24, "cells": []},
      {"rowNumber": 25, "cells": ["Fixtures — Venue"]},
      {"rowNumber": 26, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 27, "cells": ["Spot / Profile", "", "12", "Robe iForte LTX", "", "", "Sidelight"]},
      {"rowNumber": 28, "cells": ["Beam"]},
      {"rowNumber": 29, "cells": ["Wash"]},
      {"rowNumber": 30, "cells": ["Strobe"]},
      {"rowNumber": 31, "cells": ["Followspot"]},
      {"rowNumber": 32, "cells": []},
      {"rowNumber": 33, "cells": ["Haze & Smoke"]},
      {"rowNumber": 34, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 35, "cells": ["Haze Machine", "", "4", "MDG Atme", "", "", "Hazer"]},
      {"rowNumber": 36, "cells": ["Fog Machine", "", "2", "MDG ME1", "", "", "Fog"]},
      {"rowNumber": 37, "cells": ["Low Fog", "", "4", "Look Viper NT", "", "", "Low Fog"]},
      {"rowNumber": 38, "cells": ["Cracked Oil"]},
      {"rowNumber": 39, "cells": []},
      {"rowNumber": 40, "cells": ["Controls"]},
      {"rowNumber": 41, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 42, "cells": ["Console", "", "2", "GrandMA3 Fullsize", "", "", "Latest Software Version"]},
      {"rowNumber": 43, "cells": ["NPU / Processing"]},
      {"rowNumber": 44, "cells": ["UPS Backup", "", "2", "UPS 1000W", "", "", "Backup Power"]},
      {"rowNumber": 45, "cells": ["Timecode System"]},
      {"rowNumber": 46, "cells": []},
      {"rowNumber": 47, "cells": ["Followspot Details"]},
      {"rowNumber": 48, "cells": ["Followspot Type:"]},
      {"rowNumber": 49, "cells": ["Followspot Colors:", "", "e.g. L130/L201/L205"]},
      {"rowNumber": 50, "cells": ["Operated From:", "", "e.g. FOH Platform"]},
      {"rowNumber": 51, "cells": []},
      {"rowNumber": 52, "cells": ["Fixture Totals"]},
      {"rowNumber": 53, "cells": ["Total Fixtures:", "", "count per zone above"]},
      {"rowNumber": 54, "cells": ["Total DMX Universes:"]},
      {"rowNumber": 55, "cells": ["Total Power (kW):"]},
      {"rowNumber": 56, "cells": []},
      {"rowNumber": 57, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 58, "cells": []},
      {"rowNumber": 59, "cells": []},
      {"rowNumber": 60, "cells": []},
      {"rowNumber": 61, "cells": []},
      {"rowNumber": 62, "cells": ["Insert Lighting Plot / Fixture Overview here"]},
    ],
    "metrics": {
      "sections": 22,
      "quantityTotal": 323.0
    },
    "sections": ["Fixtures — Stage", "Hybrid", "LED FX", "Fixtures — Wings", "Wash", "Blinder", "Fixtures — Venue", "Beam", "Wash", "Strobe", "Followspot", "Haze & Smoke", "Cracked Oil", "Controls", "Timecode System", "Followspot Details", "Followspot Type:", "Fixture Totals", "Total DMX Universes:", "Total Power (kW):", "Notes / Remarks:", "Insert Lighting Plot / Fixture Overview here"]
  },
  "VIDEO - LED": {
    "title": "VIDEO - LED",
    "headline": "EC26 — Video / LED — See Attached Files",
    "rowCount": 48,
    "nonEmptyRows": 39,
    "maxCols": 9,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — VIDEO / LED — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["LED Screens"]},
      {"rowNumber": 4, "cells": ["Screen Name", "Size (m)", "Pixel Pitch", "Resolution (px)", "", "Tiles (WxH)", "Total Tiles", "Signal", "Creative Shape"]},
      {"rowNumber": 5, "cells": ["VX10 DJ Booth", "12.0x1.0m", "3.9MM", "", "", "24x1", "24", "#1"]},
      {"rowNumber": 6, "cells": ["VX01 Mainscreen", "19.0x8.0m", "3.9MM", "", "", "38x8", "304", "#1"]},
      {"rowNumber": 7, "cells": ["Main Screen Head"]},
      {"rowNumber": 8, "cells": ["VX02 Imag SL/SR", "11.0x8.0m", "3.9MM", "", "", "22x8", "176", "#2"]},
      {"rowNumber": 9, "cells": ["VX03 SL/SR", "7.0x8.0m", "3.9MM", "", "", "14x8", "112", "#2"]},
      {"rowNumber": 10, "cells": ["VX04 SL/SR", "4.0x8.0m", "3.9MM", "", "", "8x8", "64", "#2"]},
      {"rowNumber": 11, "cells": ["VX05 SL/SR", "3.0x8.0m", "3.9MM", "", "", "6x8", "48", "#2"]},
      {"rowNumber": 12, "cells": ["VX06 SL/SR", "2.0x8.0m", "3.9MM", "", "", "4x8", "32", "#2"]},
      {"rowNumber": 13, "cells": ["VX07 SL/SR", "1.5x8.0m", "3.9MM", "", "", "3x8", "24", "#2"]},
      {"rowNumber": 14, "cells": ["VX08 SL/SR", "1.0x8.0m", "3.9MM", "", "", "2x8", "16", "#2"]},
      {"rowNumber": 15, "cells": ["VX09 Header", "40.0x1.5m", "3.9MM Mesh", "", "", "40x3", "120", "#1", "Vertical"]},
      {"rowNumber": 16, "cells": []},
      {"rowNumber": 17, "cells": ["Video Controls & Processing"]},
      {"rowNumber": 18, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 19, "cells": ["LED Processor", "", "", "", "", "", "e.g. Barco E2"]},
      {"rowNumber": 20, "cells": ["Media Server", "", "1", "SwitcherPixelHueQ8", "", "", "LED Processor / Switcher"]},
      {"rowNumber": 21, "cells": ["Signal Distribution", "", "", "Resolume Arena (House VJ + Guest VJs)", "", "", "Media Server"]},
      {"rowNumber": 22, "cells": ["Preview Monitors", "", "1", "NovaStar MX30", "", "", "LED Processing"]},
      {"rowNumber": 23, "cells": ["Confidence Monitors", "", "", "Lightware UBEX-PRO20-HDMI-F110", "", "", "Extender"]},
      {"rowNumber": 24, "cells": ["Camera Controller"]},
      {"rowNumber": 25, "cells": ["", "", "2", "EP4 Fiber Extender", "", "", "Fiber set"]},
      {"rowNumber": 26, "cells": ["Signal Mapping"]},
      {"rowNumber": 27, "cells": ["HDMI Signal #1:", "", "Resolution @ Hz → destination"]},
      {"rowNumber": 28, "cells": ["HDMI Signal #2:", "", "Resolution @ Hz → destination"]},
      {"rowNumber": 29, "cells": ["HDMI Signal #3:", "", "HDMI 2.0 3840x2160 @60Hz → VX01 Mainscreen // VX10 DJ Booth // VX09 Header"]},
      {"rowNumber": 30, "cells": ["HDMI Signal #4:", "", "HDMI 2.0 3840x2160 @60Hz → VX02 Imag // VX03-08 Towers (SL/SR)"]},
      {"rowNumber": 31, "cells": []},
      {"rowNumber": 32, "cells": ["Cameras"]},
      {"rowNumber": 33, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 34, "cells": ["Camera 1"]},
      {"rowNumber": 35, "cells": ["Camera 2"]},
      {"rowNumber": 36, "cells": ["Camera 3", "", "8", "GrassValley LDK 8000"]},
      {"rowNumber": 37, "cells": ["Camera Controller", "", "1", "MB50XL JIB / Crane"]},
      {"rowNumber": 38, "cells": ["SDI Mixer"]},
      {"rowNumber": 39, "cells": []},
      {"rowNumber": 40, "cells": ["Power Requirement — Video"]},
      {"rowNumber": 41, "cells": ["Total Video Power (kW):"]},
      {"rowNumber": 42, "cells": []},
      {"rowNumber": 43, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 44, "cells": []},
      {"rowNumber": 45, "cells": []},
      {"rowNumber": 46, "cells": []},
      {"rowNumber": 47, "cells": []},
      {"rowNumber": 48, "cells": ["Insert Video Schedule / Signal Flow / Pixel Mapping here"]},
    ],
    "metrics": {
      "sections": 11,
      "quantityTotal": 933.0
    },
    "sections": ["Main Screen Head", "Video Controls & Processing", "Camera Controller", "Signal Mapping", "Cameras", "Camera 1", "Camera 2", "Power Requirement — Video", "Total Video Power (kW):", "Notes / Remarks:", "Insert Video Schedule / Signal Flow / Pixel Mapping here"]
  },
  "LASER": {
    "title": "LASER",
    "headline": "EC26 — Laser — See Attached Files",
    "rowCount": 32,
    "nonEmptyRows": 24,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — LASER — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Laser Units"]},
      {"rowNumber": 4, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 5, "cells": ["Laser RGB (Full Color)", "", "10", "Laserworld 30W RGB", "", "", "Full Color, FB4-equipped"]},
      {"rowNumber": 6, "cells": ["Laser Single Color"]},
      {"rowNumber": 7, "cells": ["Laser Aerial"]},
      {"rowNumber": 8, "cells": ["Laser Graphics"]},
      {"rowNumber": 9, "cells": []},
      {"rowNumber": 10, "cells": ["Laser Control"]},
      {"rowNumber": 11, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 12, "cells": ["Laser Controller", "", "1", "GrandMA 2 Light", "", "", "Console for laser control"]},
      {"rowNumber": 13, "cells": ["Laser Software", "", "1", "Rosendahl MIF4", "", "", "Midi Timecode"]},
      {"rowNumber": 14, "cells": ["ILDA / Network"]},
      {"rowNumber": 15, "cells": ["Safety / E-Stop"]},
      {"rowNumber": 16, "cells": []},
      {"rowNumber": 17, "cells": ["Smoke for Laser"]},
      {"rowNumber": 18, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 19, "cells": ["Stadium Fogger", "", "8", "Smoke Factory Tour Hazer II / Antari Z3000", "", "", "Stadium foggers"]},
      {"rowNumber": 20, "cells": ["Hazer"]},
      {"rowNumber": 21, "cells": []},
      {"rowNumber": 22, "cells": ["Safety & Compliance"]},
      {"rowNumber": 23, "cells": ["Laser Safety Officer:", "", "Name + Contact"]},
      {"rowNumber": 24, "cells": ["Laser Variance / Permit:", "", "Required Y/N — Reference #"]},
      {"rowNumber": 25, "cells": ["Safe Zones / No-Go Areas:", "", "Description"]},
      {"rowNumber": 26, "cells": ["Audience Scanning:", "", "Y/N — Max exposure"]},
      {"rowNumber": 27, "cells": []},
      {"rowNumber": 28, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 29, "cells": []},
      {"rowNumber": 30, "cells": []},
      {"rowNumber": 31, "cells": []},
      {"rowNumber": 32, "cells": ["Insert Laser Plot / Safety Zone Map here"]},
    ],
    "metrics": {
      "sections": 11,
      "quantityTotal": 20.0
    },
    "sections": ["Laser Units", "Laser Single Color", "Laser Aerial", "Laser Graphics", "Laser Control", "Safety / E-Stop", "Smoke for Laser", "Hazer", "Safety & Compliance", "Notes / Remarks:", "Insert Laser Plot / Safety Zone Map here"]
  },
  "SFX - PYRO": {
    "title": "SFX - PYRO",
    "headline": "EC26 — SFX / Pyro — See Attached Files",
    "rowCount": 35,
    "nonEmptyRows": 28,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — SFX / PYRO — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["SFX Equipment"]},
      {"rowNumber": 4, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 5, "cells": ["CO2 Jets", "", "12", "Eco Jets", "", "", "CO2 Jets"]},
      {"rowNumber": 6, "cells": ["Confetti Cannons", "", "6", "G-Flames"]},
      {"rowNumber": 7, "cells": ["Cryo Jets", "", "6", "Stadium Shots"]},
      {"rowNumber": 8, "cells": ["Flame Projectors", "", "18", "Wave Flames", "", "", "12pcs + 6pcs Towers on Stage"]},
      {"rowNumber": 9, "cells": ["Sparkular / Cold Sparks", "", "6", "Sparkular", "", "", "Cold Sparks"]},
      {"rowNumber": 10, "cells": ["Streamer Cannons"]},
      {"rowNumber": 11, "cells": ["Bubble Machines"]},
      {"rowNumber": 12, "cells": ["Wind Machines"]},
      {"rowNumber": 13, "cells": ["Snow Machines"]},
      {"rowNumber": 14, "cells": []},
      {"rowNumber": 15, "cells": ["Pyrotechnics"]},
      {"rowNumber": 16, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 17, "cells": ["Mortars / Mines"]},
      {"rowNumber": 18, "cells": ["Gerbs / Fountains"]},
      {"rowNumber": 19, "cells": ["Comets"]},
      {"rowNumber": 20, "cells": ["Flash Pots", "", "Alexandru Bondria — +40 729 953 001 — alexandru@pyroevents.ro"]},
      {"rowNumber": 21, "cells": ["Waterfall / Niagara"]},
      {"rowNumber": 22, "cells": []},
      {"rowNumber": 23, "cells": ["Controls & Safety"]},
      {"rowNumber": 24, "cells": ["SFX Operator:", "", "Name + Contact"]},
      {"rowNumber": 25, "cells": ["Firing System:", "", "e.g. Galaxis G-Flame / Pyrodigital"]},
      {"rowNumber": 26, "cells": ["Safety / Fire Marshal:", "", "Required Y/N — Name"]},
      {"rowNumber": 27, "cells": ["Fire Extinguishers Required:", "", "Type + Qty + Location"]},
      {"rowNumber": 28, "cells": ["Safety Distance (audience):", "", "meters"]},
      {"rowNumber": 29, "cells": ["Permit / License:", "", "Reference #"]},
      {"rowNumber": 30, "cells": []},
      {"rowNumber": 31, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 32, "cells": []},
      {"rowNumber": 33, "cells": []},
      {"rowNumber": 34, "cells": []},
      {"rowNumber": 35, "cells": ["Insert SFX Plot / Safety Plan here"]},
    ],
    "metrics": {
      "sections": 12,
      "quantityTotal": 48.0
    },
    "sections": ["Streamer Cannons", "Bubble Machines", "Wind Machines", "Snow Machines", "Pyrotechnics", "Mortars / Mines", "Gerbs / Fountains", "Comets", "Waterfall / Niagara", "Controls & Safety", "Notes / Remarks:", "Insert SFX Plot / Safety Plan here"]
  },
  "POWER": {
    "title": "POWER",
    "headline": "EC26 — Power — See Attached Files",
    "rowCount": 46,
    "nonEmptyRows": 39,
    "maxCols": 9,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — POWER — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Power Supply Rules"]},
      {"rowNumber": 4, "cells": ["1. All feeds must be delivered with 5M Socapex per Position."]},
      {"rowNumber": 5, "cells": ["2. All feeds must be delivered on cable part + Connector — No chassis."]},
      {"rowNumber": 6, "cells": ["3. No mixing between Generator power & house power."]},
      {"rowNumber": 7, "cells": ["4. Scaffolding / Staging / PSU's / DMX must be grounded and linked."]},
      {"rowNumber": 8, "cells": ["5. Phase rotation must be consistent across all distros (400V Between Phases) @ 50HZ."]},
      {"rowNumber": 9, "cells": ["6. Monitor the current of the Neutral — it can be high because of LED/Video/Audio equipment."]},
      {"rowNumber": 10, "cells": ["7. Please check fuse value: MUST be 3x63A."]},
      {"rowNumber": 11, "cells": ["8. Overnight power must be supplied from 72h prior showday 1."]},
      {"rowNumber": 12, "cells": ["9. Overnight power must be supplied between show days."]},
      {"rowNumber": 13, "cells": ["10. Power for Audio / Light / Video fluctuates — supply needs to handle (heavy) fluctuations."]},
      {"rowNumber": 14, "cells": ["11. Electrician must be standby from Start Load-in Through End Load-out."]},
      {"rowNumber": 15, "cells": ["12. No Bio Diesel Allowed for Generators."]},
      {"rowNumber": 16, "cells": []},
      {"rowNumber": 17, "cells": ["Power Distribution Table"]},
      {"rowNumber": 18, "cells": ["Department", "Feed Type", "", "Connection", "", "Phase/Amps", "", "kW", "Location"]},
      {"rowNumber": 19, "cells": ["LIGHTING — Stage"]},
      {"rowNumber": 20, "cells": ["LIGHTING — Venue"]},
      {"rowNumber": 21, "cells": ["LIGHTING — Wings"]},
      {"rowNumber": 22, "cells": ["LIGHTING — FOH"]},
      {"rowNumber": 23, "cells": ["VIDEO / LED"]},
      {"rowNumber": 24, "cells": ["AUDIO — PA"]},
      {"rowNumber": 25, "cells": ["AUDIO — FOH"]},
      {"rowNumber": 26, "cells": ["AUDIO — Booth"]},
      {"rowNumber": 27, "cells": ["SFX / PYRO"]},
      {"rowNumber": 28, "cells": ["LASER"]},
      {"rowNumber": 29, "cells": ["RIGGING / MOTORS"]},
      {"rowNumber": 30, "cells": ["BACKLINE"]},
      {"rowNumber": 31, "cells": ["GUEST LIGHTS"]},
      {"rowNumber": 32, "cells": ["BROADCAST / IMAG"]},
      {"rowNumber": 33, "cells": ["GENERAL / MISC"]},
      {"rowNumber": 34, "cells": ["TOTAL"]},
      {"rowNumber": 35, "cells": []},
      {"rowNumber": 36, "cells": ["Generator / Source Info"]},
      {"rowNumber": 37, "cells": ["Generator / Main Source:", "", "Type + Capacity"]},
      {"rowNumber": 38, "cells": ["Main Distro Location:"]},
      {"rowNumber": 39, "cells": ["Backup / UPS:"]},
      {"rowNumber": 40, "cells": ["Cable Run to Stage (m):"]},
      {"rowNumber": 41, "cells": []},
      {"rowNumber": 42, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 43, "cells": []},
      {"rowNumber": 44, "cells": []},
      {"rowNumber": 45, "cells": []},
      {"rowNumber": 46, "cells": ["Insert Power Distribution Drawing here"]},
    ],
    "metrics": {
      "sections": 32,
      "quantityTotal": 0
    },
    "sections": ["Power Supply Rules", "1. All feeds must be delivered with 5M Socapex per Position.", "2. All feeds must be delivered on cable part + Connector — No chassis.", "3. No mixing between Generator power & house power.", "4. Scaffolding / Staging / PSU's / DMX must be grounded and linked.", "5. Phase rotation must be consistent across all distros (400V Between Phases) @ 50HZ.", "6. Monitor the current of the Neutral — it can be high because of LED/Video/Audio equipment.", "7. Please check fuse value: MUST be 3x63A.", "8. Overnight power must be supplied from 72h prior showday 1.", "9. Overnight power must be supplied between show days.", "10. Power for Audio / Light / Video fluctuates — supply needs to handle (heavy) fluctuations.", "11. Electrician must be standby from Start Load-in Through End Load-out.", "12. No Bio Diesel Allowed for Generators.", "Power Distribution Table", "LIGHTING — FOH", "VIDEO / LED", "AUDIO — PA", "AUDIO — FOH", "SFX / PYRO", "LASER", "RIGGING / MOTORS", "BACKLINE", "GUEST LIGHTS", "BROADCAST / IMAG", "GENERAL / MISC", "TOTAL", "Generator / Source Info", "Main Distro Location:", "Backup / UPS:", "Cable Run to Stage (m):", "Notes / Remarks:", "Insert Power Distribution Drawing here"]
  },
  "RIGGING": {
    "title": "RIGGING",
    "headline": "EC26 — Rigging — See Attached Files",
    "rowCount": 52,
    "nonEmptyRows": 43,
    "maxCols": 9,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — RIGGING — See Attached Files"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Stage & Structure"]},
      {"rowNumber": 4, "cells": ["Stage Supplier:", "", "Loudmusic — Serban Constantinescu"]},
      {"rowNumber": 5, "cells": ["Stage Type / System:", "", "TGV1 Megaforce"]},
      {"rowNumber": 6, "cells": ["Stage Width (m):", "", "87.40 (overall incl. wings) / Stage area: 40.40"]},
      {"rowNumber": 7, "cells": ["Stage Depth (m):", "", "34.00 (overall) / Stage area: 18.65"]},
      {"rowNumber": 8, "cells": ["Stage Height (m):", "", "18.50"]},
      {"rowNumber": 9, "cells": ["Wing SL (m):"]},
      {"rowNumber": 10, "cells": ["Wing SR (m):"]},
      {"rowNumber": 11, "cells": ["Proscenium Height (m):"]},
      {"rowNumber": 12, "cells": ["Grid Height (m):"]},
      {"rowNumber": 13, "cells": ["FOH Distance (m):", "", "46.00"]},
      {"rowNumber": 14, "cells": ["Pit / Barrier Type:"]},
      {"rowNumber": 15, "cells": ["Roof Type:", "", "TGV1 Megaforce"]},
      {"rowNumber": 16, "cells": ["Deck Surface:"]},
      {"rowNumber": 17, "cells": ["Loading Dock:", "", "Main Dock: 7.00m x 10.00m / SL Audio Dock: 8.00m x 2.00m"]},
      {"rowNumber": 18, "cells": ["Height of Podium:", "", "2.40"]},
      {"rowNumber": 19, "cells": ["Clearance under Roof:"]},
      {"rowNumber": 20, "cells": ["Total Area of Stage:", "", "Width: 40.40m  Depth: 18.65m"]},
      {"rowNumber": 21, "cells": []},
      {"rowNumber": 22, "cells": ["Rigging Points / Motors"]},
      {"rowNumber": 23, "cells": ["Truss / Point", "", "Type", "", "Max Load (kg)", "", "Truss Width (m)", "Trim Height (m)", "Position from DS"]},
      {"rowNumber": 24, "cells": ["Guest LX 1"]},
      {"rowNumber": 25, "cells": ["Guest LX 2"]},
      {"rowNumber": 26, "cells": ["Guest LX 3"]},
      {"rowNumber": 27, "cells": ["Guest LX 4"]},
      {"rowNumber": 28, "cells": ["Front Truss"]},
      {"rowNumber": 29, "cells": ["Mid Truss"]},
      {"rowNumber": 30, "cells": ["Rear Truss"]},
      {"rowNumber": 31, "cells": ["Side Truss SR"]},
      {"rowNumber": 32, "cells": ["Side Truss SL"]},
      {"rowNumber": 33, "cells": ["Cable Truss"]},
      {"rowNumber": 34, "cells": ["FOH Truss"]},
      {"rowNumber": 35, "cells": ["Custom"]},
      {"rowNumber": 36, "cells": []},
      {"rowNumber": 37, "cells": ["Rigging Hardware"]},
      {"rowNumber": 38, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 39, "cells": ["Motors (Chain Hoist)", "", "", "", "", "", "e.g. Prolyte HDTV 1000kg"]},
      {"rowNumber": 40, "cells": ["Truss System"]},
      {"rowNumber": 41, "cells": ["Bridles / Steels"]},
      {"rowNumber": 42, "cells": ["Shackles & Hardware"]},
      {"rowNumber": 43, "cells": ["Spansets / Round Slings"]},
      {"rowNumber": 44, "cells": []},
      {"rowNumber": 45, "cells": ["Rigging Note:", "", "*** Without approval, No Rigging ***"]},
      {"rowNumber": 46, "cells": []},
      {"rowNumber": 47, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 48, "cells": []},
      {"rowNumber": 49, "cells": []},
      {"rowNumber": 50, "cells": []},
      {"rowNumber": 51, "cells": []},
      {"rowNumber": 52, "cells": ["Insert Rigging Plan / Truss Layout / Weight Plot here"]},
    ],
    "metrics": {
      "sections": 27,
      "quantityTotal": 66.9
    },
    "sections": ["Stage & Structure", "Wing SL (m):", "Wing SR (m):", "Proscenium Height (m):", "Grid Height (m):", "Pit / Barrier Type:", "Deck Surface:", "Clearance under Roof:", "Rigging Points / Motors", "Guest LX 1", "Guest LX 2", "Guest LX 3", "Guest LX 4", "Front Truss", "Mid Truss", "Rear Truss", "Side Truss SR", "Side Truss SL", "Cable Truss", "Custom", "Rigging Hardware", "Truss System", "Bridles / Steels", "Shackles & Hardware", "Spansets / Round Slings", "Notes / Remarks:", "Insert Rigging Plan / Truss Layout / Weight Plot here"]
  },
  "BACKLINE": {
    "title": "BACKLINE",
    "headline": "EC26 — Backline",
    "rowCount": 27,
    "nonEmptyRows": 23,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — BACKLINE"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Standard Backline"]},
      {"rowNumber": 4, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 5, "cells": ["DJ Mixer"]},
      {"rowNumber": 6, "cells": ["DJ Players (CDJ)"]},
      {"rowNumber": 7, "cells": ["Turntables"]},
      {"rowNumber": 8, "cells": ["Keyboard / Synth"]},
      {"rowNumber": 9, "cells": ["Guitar Amp"]},
      {"rowNumber": 10, "cells": ["Bass Amp"]},
      {"rowNumber": 11, "cells": ["Drum Kit"]},
      {"rowNumber": 12, "cells": ["Drum Risers"]},
      {"rowNumber": 13, "cells": ["Music Stands"]},
      {"rowNumber": 14, "cells": ["DI Boxes"]},
      {"rowNumber": 15, "cells": ["Power Strips (Stage)"]},
      {"rowNumber": 16, "cells": []},
      {"rowNumber": 17, "cells": ["Headliner Backline Requests"]},
      {"rowNumber": 18, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 19, "cells": ["Custom Request 1"]},
      {"rowNumber": 20, "cells": ["Custom Request 2"]},
      {"rowNumber": 21, "cells": ["Custom Request 3"]},
      {"rowNumber": 22, "cells": ["Custom Request 4"]},
      {"rowNumber": 23, "cells": []},
      {"rowNumber": 24, "cells": ["Backline Power"]},
      {"rowNumber": 25, "cells": ["Backline Power Requirement:"]},
      {"rowNumber": 26, "cells": []},
      {"rowNumber": 27, "cells": ["Notes / Remarks:"]},
    ],
    "metrics": {
      "sections": 18,
      "quantityTotal": 0
    },
    "sections": ["EC26 — BACKLINE", "Standard Backline", "Turntables", "Keyboard / Synth", "Guitar Amp", "Bass Amp", "Drum Kit", "Drum Risers", "Music Stands", "Power Strips (Stage)", "Headliner Backline Requests", "Custom Request 1", "Custom Request 2", "Custom Request 3", "Custom Request 4", "Backline Power", "Backline Power Requirement:", "Notes / Remarks:"]
  },
  "BROADCAST": {
    "title": "BROADCAST",
    "headline": "EC26 — Broadcast / IMAG",
    "rowCount": 29,
    "nonEmptyRows": 25,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — BROADCAST / IMAG"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Cameras"]},
      {"rowNumber": 4, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 5, "cells": ["Camera 1 (FOH)", "", "8", "GrassValley LDK 8000"]},
      {"rowNumber": 6, "cells": ["Camera 2 (Stage SR)"]},
      {"rowNumber": 7, "cells": ["Camera 3 (Stage SL)"]},
      {"rowNumber": 8, "cells": ["Camera 4 (Crane/Jib)"]},
      {"rowNumber": 9, "cells": ["Camera 5 (Roaming)", "", "1", "MB50XL JIB / Crane"]},
      {"rowNumber": 10, "cells": ["Robotic / PTZ Cam"]},
      {"rowNumber": 11, "cells": []},
      {"rowNumber": 12, "cells": ["Broadcast Control"]},
      {"rowNumber": 13, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 14, "cells": ["Vision Mixer / Switcher", "", "1", "Van Hool 927 SD3 HD XXL", "", "", "OB Van"]},
      {"rowNumber": 15, "cells": ["Multiview Monitor"]},
      {"rowNumber": 16, "cells": ["Record Deck"]},
      {"rowNumber": 17, "cells": ["Stream Encoder"]},
      {"rowNumber": 18, "cells": ["Graphics / CG System"]},
      {"rowNumber": 19, "cells": ["Tally System"]},
      {"rowNumber": 20, "cells": ["Intercom (Broadcast)"]},
      {"rowNumber": 21, "cells": []},
      {"rowNumber": 22, "cells": ["Signal & Infrastructure"]},
      {"rowNumber": 23, "cells": ["SDI Runs to Stage:"]},
      {"rowNumber": 24, "cells": ["Fiber Runs:"]},
      {"rowNumber": 25, "cells": ["Broadcast Truck Location:"]},
      {"rowNumber": 26, "cells": ["Internet Upload Speed:"]},
      {"rowNumber": 27, "cells": ["Stream Platform:", "", "e.g. YouTube / Twitch / Custom"]},
      {"rowNumber": 28, "cells": []},
      {"rowNumber": 29, "cells": ["Notes / Remarks:"]},
    ],
    "metrics": {
      "sections": 18,
      "quantityTotal": 10.0
    },
    "sections": ["EC26 — BROADCAST / IMAG", "Cameras", "Camera 2 (Stage SR)", "Camera 3 (Stage SL)", "Camera 4 (Crane/Jib)", "Robotic / PTZ Cam", "Broadcast Control", "Multiview Monitor", "Record Deck", "Stream Encoder", "Graphics / CG System", "Tally System", "Intercom (Broadcast)", "Signal & Infrastructure", "Fiber Runs:", "Broadcast Truck Location:", "Internet Upload Speed:", "Notes / Remarks:"]
  },
  "STAGING": {
    "title": "STAGING",
    "headline": "EC26 — Staging / Infrastructure",
    "rowCount": 42,
    "nonEmptyRows": 33,
    "maxCols": 7,
    "rows": [
      {"rowNumber": 1, "cells": ["EC26 — STAGING / INFRASTRUCTURE"]},
      {"rowNumber": 2, "cells": []},
      {"rowNumber": 3, "cells": ["Stage Structure — Supplier Info"]},
      {"rowNumber": 4, "cells": ["Stage Supplier:", "", "Loudmusic — Serban Constantinescu (+40 737 203 060, serban@loudmusic.ro)"]},
      {"rowNumber": 5, "cells": ["Structure Type:", "", "TGV1 Megaforce"]},
      {"rowNumber": 6, "cells": ["Roof System:", "", "TGV1 Megaforce Roof"]},
      {"rowNumber": 7, "cells": ["Total Height:", "", "18.50m total height"]},
      {"rowNumber": 8, "cells": ["Overall Size incl. Wings:", "", "Width: 87.40m Depth: 34.00m (incl. wings)"]},
      {"rowNumber": 9, "cells": []},
      {"rowNumber": 10, "cells": ["Risers & Platforms"]},
      {"rowNumber": 11, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 12, "cells": ["DJ Riser", "", "", "", "", "", "WxDxH"]},
      {"rowNumber": 13, "cells": ["Drum Riser", "", "", "", "", "", "Stage: 21.00x11.00m / Catwalk: 5.00x12.50m"]},
      {"rowNumber": 14, "cells": ["B-Stage / Catwalk", "", "", "", "", "", "B-stage: 8.75x5.00m H:1.50m"]},
      {"rowNumber": 15, "cells": ["FOH Platform", "", "", "", "", "", "WxDxH"]},
      {"rowNumber": 16, "cells": ["Delay Tower Platform"]},
      {"rowNumber": 17, "cells": ["Followspot Platform"]},
      {"rowNumber": 18, "cells": ["Camera Platform"]},
      {"rowNumber": 19, "cells": []},
      {"rowNumber": 20, "cells": ["Dressing & Scenic"]},
      {"rowNumber": 21, "cells": ["Equipment", "", "Qty", "Brand / Model", "", "", "Specs / Notes"]},
      {"rowNumber": 22, "cells": ["Star Cloth / Drapes"]},
      {"rowNumber": 23, "cells": ["Kabuki Drop"]},
      {"rowNumber": 24, "cells": ["Scenic Elements"]},
      {"rowNumber": 25, "cells": ["Banner / Signage", "", "SL: 7m x 8m / SR: 7m x 8m"]},
      {"rowNumber": 26, "cells": ["Truss Cover / Sleeve", "", "FOH: 12.00m x 8.00m — 46.00m from stage lip"]},
      {"rowNumber": 27, "cells": []},
      {"rowNumber": 28, "cells": ["Site Infrastructure"]},
      {"rowNumber": 29, "cells": ["Monitor World Area:", "", "Location + Size"]},
      {"rowNumber": 30, "cells": ["FOH Area:", "", "Location + Size"]},
      {"rowNumber": 31, "cells": ["Dimmer City Location:"]},
      {"rowNumber": 32, "cells": ["Cable Routes:", "", "Stage → FOH → Dimmer City"]},
      {"rowNumber": 33, "cells": ["Water / Drainage:"]},
      {"rowNumber": 34, "cells": ["Truck Access:", "", "Route + max vehicle size"]},
      {"rowNumber": 35, "cells": ["Loading Dock:"]},
      {"rowNumber": 36, "cells": []},
      {"rowNumber": 37, "cells": ["Notes / Remarks:"]},
      {"rowNumber": 38, "cells": []},
      {"rowNumber": 39, "cells": []},
      {"rowNumber": 40, "cells": []},
      {"rowNumber": 41, "cells": []},
      {"rowNumber": 42, "cells": ["Insert Stage Plan / Infrastructure Drawing / Site Map here"]},
    ],
    "metrics": {
      "sections": 16,
      "quantityTotal": 0
    },
    "sections": ["EC26 — STAGING / INFRASTRUCTURE", "Stage Structure — Supplier Info", "Risers & Platforms", "Delay Tower Platform", "Followspot Platform", "Camera Platform", "Dressing & Scenic", "Star Cloth / Drapes", "Kabuki Drop", "Scenic Elements", "Site Infrastructure", "Dimmer City Location:", "Water / Drainage:", "Loading Dock:", "Notes / Remarks:", "Insert Stage Plan / Infrastructure Drawing / Site Map here"]
  },
};

export const DASHBOARD_KPIS = {
  totalItems: 349,
  totalQty: 1475,
  departments: 10,
  scheduleDays: 14,
  tabs: 12,
  trackedItems: 349,
  project: 'EC26_Electric_Castle_Mainstage',
  venue: 'Banffy Castle Domain',
  location: 'Bonțida, Romania',
};

export const DASHBOARD_ANALYTICS = {
  departmentItems: [
    { dept: "Audio", items: 45 },
    { dept: "Lighting", items: 50 },
    { dept: "Video/LED", items: 39 },
    { dept: "Rigging", items: 43 },
    { dept: "SFX/Pyro", items: 28 },
    { dept: "Power", items: 39 },
    { dept: "Staging", items: 33 },
    { dept: "Laser", items: 24 },
    { dept: "Backline", items: 23 },
    { dept: "Broadcast", items: 25 },
  ],
  schedule: [],
};